### ISSUE TITLE
*Help* Need advice on how to change the mod

### ISSUE THREAD

**Issue by CamoSteve** [rockhymas/iberia#25]
Hello, I enjoy the deathwithconsequences concept, however for my private modpack its too hardcore. I thought adjusting the settings via the config would change the distance, but those config options are just extra distance to the base 1000. How would I approach changing the mod so the base distance is something small like 1? This way the world spawn does not change much when someone dies, but still retain random player spawning by using the existing config options for gamemode type.

Any help is appreciated.

**Comment by rockhymas** [comment]
The distance is an actual distance, not added to 1000. But after figuring out the distance, the same algorithm is used to determine a spawn point as is used when creating a new world, i.e first, iberia finds a point X blocks from the last spawn point. Then it searches for an appropriate spawning position around that (within 256 blocks).
