### ISSUE TITLE
[Conflict] v1.10.2: Hard rock incompatible with WTF Suite

### ISSUE THREAD

**Issue by nepphhh** [rockhymas/iberia#32]
With any portion of the WTF Exploration suite installed (Worldgen or gameplay pack), iberian hard rock is still present and behaves as normal except it does not have any mining slowdown.

**Comment by rockhymas** [comment]
This is actually an issue with WTF suite. Based on my looking through the code for it, If you turn off the gameplay tweaks in config, I believe it mining slowdown will work again. Is iberia:hardstone listed in the "Master Stone List" config for WTF? If so, you could remove it, and that would likely fix the issue as well.

**Comment by nepphhh** [comment]
Unfortunately, I'm trying to have both co-exist, where there's hard rock but it also will fracture into cobblestone. 

iberia:hardstone is not in the stone list for WTF, and right now, mining hard stone (at regular speed) does not fracture it into cobblestone. I'm probably going to tweak that.

Even when I had all the gameplay tweaks disabled or uninstalled, hard stone still didn't work. I'll go poke at WTF.
